version: 2

before:
  hooks:
    - ./gen/gen.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/alex-brook/composefork/cmd.version={{.Version}}
      - -X github.com/alex-brook/composefork/cmd.commit={{.Commit}}
      - -X github.com/alex-brook/composefork/cmd.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
